#! /bin/sh

#sxhkd &

#feh --bg-fill ~/Pictures/bmw.jpg &
#feh --bg-fill ~/Pictures/wood-forest-stack-stacked.jpg &
feh --bg-fill ~/Dropbox/Thuis/bureau\'s/fire.jpg &


polybar main &
nm-applet &
conky &
compton -c --vsync opengl & 
dropbox &
# /usr/lib/notify-osd/notify-osd &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor LVDS -d I II III IV V

if xrandr | grep "DisplayPort-2 connected"; then
	bspc monitor DisplayPort-2 -d VI VII VIII IX X
	polybar hdmi &
fi

if xrandr | grep "DisplayPort-0 connected"; then
	bspc monitor DisplayPort-0 -d VI VII VIII IX X
	polybar dp &
fi

if xrandr | grep "VGA-0 connected"; then
	bspc monitor VGA-0 -d VI VII VIII IX X
	polybar vga &
fi

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         20
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config remove_disabled_monitor true
bspc config remove_unplugged_monitor true
bspc config click_to_focus 		 true
#bspc config pointer_action1 	move
#bspc config pointer_action2 	resize_side
#bspc config pointer_action3 	resize_corner

bspc config normal_border_color "#131313"
bspc config focused_border_color "#eb9605"
bspc config presel_feedback_color "#eb9605"

bspc rule -a Galculator state=floating
bspc rule -a Gimp state=floating follow=on
bspc rule -a Java state=floating follow=on
bspc rule -a GitKraken state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
